// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PizzaX.Infrastructure.Data;

#nullable disable

namespace PizzaX.Infrastructure.Migrations
{
    [DbContext(typeof(PizzaXDbContext))]
    partial class PizzaXDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PizzaX.Domain.Entities.Drink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DrinkType")
                        .HasColumnType("int")
                        .HasColumnName("Type");

                    b.Property<byte[]>("Image")
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Drinks");
                });

            modelBuilder.Entity("PizzaX.Domain.Entities.Fries", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Image")
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Fries");
                });

            modelBuilder.Entity("PizzaX.Domain.Entities.Pizza", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Image")
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("Size")
                        .HasColumnType("int")
                        .HasColumnName("Size");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("VarietyId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("VarietyId");

                    b.ToTable("Pizzas");
                });

            modelBuilder.Entity("PizzaX.Domain.Entities.PizzaVariety", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("PizzaVarieties");
                });

            modelBuilder.Entity("PizzaX.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("ProfilePic")
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserRole")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(2)
                        .HasColumnName("Role");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PizzaX.Domain.Entities.Drink", b =>
                {
                    b.OwnsOne("PizzaX.Domain.ValueObjects.Pizza.Price", "Price", b1 =>
                        {
                            b1.Property<Guid>("DrinkId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("UnitPrice")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Price");

                            b1.HasKey("DrinkId");

                            b1.ToTable("Drinks");

                            b1.WithOwner()
                                .HasForeignKey("DrinkId");
                        });

                    b.OwnsOne("PizzaX.Domain.ValueObjects.Product.Quantity", "Quantity", b1 =>
                        {
                            b1.Property<Guid>("DrinkId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Value")
                                .HasColumnType("int")
                                .HasColumnName("Quantity");

                            b1.HasKey("DrinkId");

                            b1.ToTable("Drinks");

                            b1.WithOwner()
                                .HasForeignKey("DrinkId");
                        });

                    b.OwnsOne("PizzaX.Domain.ValueObjects.Drink.DrinkDetails", "DrinkDetails", b1 =>
                        {
                            b1.Property<Guid>("DrinkId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Company")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Company");

                            b1.Property<string>("RetailerContactNumber")
                                .HasColumnType("nvarchar(450)")
                                .HasColumnName("Contact");

                            b1.HasKey("DrinkId");

                            b1.HasIndex("RetailerContactNumber")
                                .IsUnique()
                                .HasFilter("[Contact] IS NOT NULL");

                            b1.ToTable("Drinks");

                            b1.WithOwner()
                                .HasForeignKey("DrinkId");
                        });

                    b.Navigation("DrinkDetails")
                        .IsRequired();

                    b.Navigation("Price")
                        .IsRequired();

                    b.Navigation("Quantity")
                        .IsRequired();
                });

            modelBuilder.Entity("PizzaX.Domain.Entities.Fries", b =>
                {
                    b.OwnsOne("PizzaX.Domain.ValueObjects.Pizza.Price", "Price", b1 =>
                        {
                            b1.Property<Guid>("FriesId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("UnitPrice")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Price");

                            b1.HasKey("FriesId");

                            b1.ToTable("Fries");

                            b1.WithOwner()
                                .HasForeignKey("FriesId");
                        });

                    b.OwnsOne("PizzaX.Domain.ValueObjects.Product.Quantity", "Quantity", b1 =>
                        {
                            b1.Property<Guid>("FriesId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Value")
                                .HasColumnType("int")
                                .HasColumnName("Quantity");

                            b1.HasKey("FriesId");

                            b1.ToTable("Fries");

                            b1.WithOwner()
                                .HasForeignKey("FriesId");
                        });

                    b.Navigation("Price")
                        .IsRequired();

                    b.Navigation("Quantity")
                        .IsRequired();
                });

            modelBuilder.Entity("PizzaX.Domain.Entities.Pizza", b =>
                {
                    b.HasOne("PizzaX.Domain.Entities.PizzaVariety", "Variety")
                        .WithMany("Pizzas")
                        .HasForeignKey("VarietyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("PizzaX.Domain.ValueObjects.Pizza.Price", "Price", b1 =>
                        {
                            b1.Property<Guid>("PizzaId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("UnitPrice")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Price");

                            b1.HasKey("PizzaId");

                            b1.ToTable("Pizzas");

                            b1.WithOwner()
                                .HasForeignKey("PizzaId");
                        });

                    b.OwnsOne("PizzaX.Domain.ValueObjects.Product.Quantity", "Quantity", b1 =>
                        {
                            b1.Property<Guid>("PizzaId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Value")
                                .HasColumnType("int")
                                .HasColumnName("Quantity");

                            b1.HasKey("PizzaId");

                            b1.ToTable("Pizzas");

                            b1.WithOwner()
                                .HasForeignKey("PizzaId");
                        });

                    b.Navigation("Price")
                        .IsRequired();

                    b.Navigation("Quantity")
                        .IsRequired();

                    b.Navigation("Variety");
                });

            modelBuilder.Entity("PizzaX.Domain.Entities.User", b =>
                {
                    b.OwnsOne("PizzaX.Domain.ValueObjects.User.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(450)")
                                .HasColumnName("Email");

                            b1.HasKey("UserId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("PizzaX.Domain.ValueObjects.User.Password", "Password", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Hash")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Password");

                            b1.HasKey("UserId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("Password")
                        .IsRequired();
                });

            modelBuilder.Entity("PizzaX.Domain.Entities.PizzaVariety", b =>
                {
                    b.Navigation("Pizzas");
                });
#pragma warning restore 612, 618
        }
    }
}
